---
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: default
  labels:
    app: bitcoind
    type: bitcoind
spec:
  ports:
  - port: 8332
    targetPort: 8332
    name: rpc-port
  - port: 8333
    targetPort: 8333
    name: port
  selector:
    app: bitcoind
    type: bitcoind
