---
apiVersion: v1
kind: Service
metadata:
  name: electrs-blockstream
  namespace: default
  labels:
    app: electrs-blockstream
    type: electrs-blockstream
spec:
  type: LoadBalancer
  ports:
  - port: 60001
    targetPort: 60001
    name: electrum-rpc
  - port: 3000
    targetPort: 3000
    name: http-api
  selector:
    app: electrs-blockstream
    type: electrs-blockstream
